# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CareOfMySelf' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CareOfMySelf
    pod 'Socket.IO-Client-Swift'
    pod 'Alamofire'
    pod 'Moya'
    pod 'SwiftyJSON'
#    pod 'SVProgressHUD'
  target 'CareOfMySelfTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CareOfMySelfUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
